### ISSUE TITLE
Provide circe codecs for MetricsDef

### ISSUE THREAD

**Issue by vpodlnk** [PlayQ/d4s#56]
We removed circe dependency in metrics module, but it very convenient to have a possibility to pass metrics over HTTP. We could provide circe codecs for MetricsDef in circle module.

**Comment by aliubymov-playq** [comment]
I think it's unnecessary. Users can easily define their own codecs. (E.g. with uPickle)
Also, you adding codecs into `d4s-circe` (at  #57), which is not good (What if user don't want to have d4s circe codecs).

**Comment by neko-kai** [comment]
Well, the codecs are in a separate object, they're not in scope unless you `import d4s.circe.MetricCodecs`.
Also, you can make circe an `Optional` dependency and make the instances optional, like distage does for `DIEffect` - https://blog.7mind.io/no-more-orphans.html

**Comment by aliubymov-playq** [comment]
Okay then. I've just thought that it's easier to define codecs in your codebase, than adding `d4s-circe` deps (even optional). Also, we can use `MetricsDef.encode` method to create JSON for metric (but this method does not escapes `"` character.), and `MetricsDef.decode` to decode from JSON string.

**Comment by vpodlnk** [comment]
Yup, @aliubymov-playq is right, we could implement codecs like this on client side
```scala
implicit val enc: Encoder[MetricDef] = Encoder[String].contramap[MetricDef](MetricDef.encode)
implicit val dec: Decoder[MetricDef] = Decoder[String].emap(m => MetricDef.decode(m).left.map(_.getMessage))
```
On the other hand it's very convenient to have something like this by default, so users bother themself with such stuff. Still it's not clear to me how to apply this trick from Izumi. I mean we should provide type like this
```scala
trait MetricCodec {
 def encode = ???
 def decode = ???
}
```
